---
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test

